version: '3'
services:
  java-srv:
    build:
      context: java-srv
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"

  db:
    build: db
    environment:
      - POSTGRES_DB=animal
      - POSTGRES_USER=maria
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
